name: Trigger API on Discussion Comment to Use Bot.

on:
  discussion_comment:
    types: [created]

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call your API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"content": "YusJade`s Blog receive a new comment#${{ github.event.comment.node_id }} on ${{ github.event.discussion.node_id }}: ${{ github.event.comment.body }} "}' \
            http://123.207.43.230:25595/api/message-board
