name: Trigger API on Discussion Comment to Use Bot.

on:
  discussion_comment:
    types: [created]

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call your API
        run: |
          curl -X POST 'http://123.207.43.230/v1/workflows/run' \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{secrets.DIFY_API_KEY}}" \
            -d '{ 
                  "inputs" : {
                    "comment_id":  "${{ github.event.comment.node_id }}", 
                    "discussion_id": "${{ github.event.discussion.node_id }}",
                    "comment_body": "${{ github.event.comment.body }}"
                  },
                  "response_mode": "blocking"
                }'

