name: 调用 Dify API 以使用智能回复体

on:
  discussion_comment:
    types: [created]

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: check top comment
        id: check_comment
        run: |
          # 检查是否是顶级评论
          if [ -z "${{ github.event.comment.in_reply_to_id }}" ]; then
            echo "comment_type=top_level" >> $GITHUB_OUTPUT
          else
            echo "comment_type=reply" >> $GITHUB_OUTPUT
          fi

      - name: call reply robot
        if: steps.check_comment.outputs.comment_type == 'top_level'
        run: |
          curl -X POST 'http://123.207.43.230/v1/workflows/run' \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{secrets.DIFY_API_KEY}}" \
            -d '{ 
                  "inputs" : {
                    "comment_id":  "${{ github.event.comment.node_id }}", 
                    "discussion_id": "${{ github.event.discussion.node_id }}",
                    "comment_body": "${{ github.event.comment.body }}"
                  },
                  "response_mode": "blocking",
                  "user": "robot"
                }'
